# Generated by Django 3.1 on 2020-08-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='number_of_lesson',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='part_of_the_lesson',
            field=models.PositiveIntegerField(),
        ),
    ]
