# Generated by Django 3.1 on 2020-08-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200827_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='css',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='js',
            field=models.TextField(null=True),
        ),
    ]
