# Generated by Django 3.1 on 2020-08-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200827_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='css',
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='js',
        ),
        migrations.AddField(
            model_name='lesson',
            name='css',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='js',
            field=models.TextField(null=True),
        ),
    ]
