# Generated by Django 3.1 on 2020-10-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_useranswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
